In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
arrhythmia_data = pd.read_csv('arrhythmia.csv', header = None)

#I will use this dataset, although I have no idea what the column headers are supposed to mean, removed them
#from what I can gather from the discussion board, the headers don't really matter anyway.
#tried converting the dataframe into a numpy array

arrhythmia_array = arrhythmia_data.to_numpy()
print(arrhythmia_array)

[[75 0 190 ... 23.3 49.4 8]
 [56 1 165 ... 20.4 38.8 6]
 [54 0 172 ... 12.3 49.0 10]
 ...
 [36 0 166 ... -44.2 -33.2 2]
 [32 1 155 ... 25.0 46.6 1]
 [78 1 160 ... 21.3 32.8 1]]


In [8]:
#Here I am following the article from the required readings by Lorraine Li, it was one of the few required readings I was able to understand

from sklearn.cluster import KMeans

km = KMeans(
    n_clusters=3, init='random',
    n_init=10, max_iter=300, 
    tol=1e-04, random_state=0
)
y_km = km.fit_predict(arrhythmia_array)

# Plotting the clusters
# I don't understand how it knows how to plot this 280 column table into 3 clusters, or however many clusters
# In the discussion board you mention that there are "16 classes"  - im not seeing that and do not know what that is in reference to

plt.scatter(
    arrhythmia_array[y_km == 0, 0], arrhythmia_array[y_km == 0, 1],
    s=50, c='lightgreen',
    marker='s', edgecolor='black',
    label='cluster 1'
)

plt.scatter(
    arrhythmia_array[y_km == 1, 0], arrhythmia_array[y_km == 1, 1],
    s=50, c='orange',
    marker='o', edgecolor='black',
    label='cluster 2'
)

plt.scatter(
    arrhythmia_array[y_km == 2, 0], arrhythmia_array[y_km == 2, 1],
    s=50, c='lightblue',
    marker='v', edgecolor='black',
    label='cluster 3'
)

# plotting the centroids
plt.scatter(
    km.cluster_centers_[:, 0], km.cluster_centers_[:, 1],
    s=250, marker='*',
    c='red', edgecolor='black',
    label='centroids'
)

plt.legend(scatterpoints=1)
plt.grid()
plt.show()

#getting an error - I think something with not being able to convert a string to a float, why does it need to be a float?
#I think the main problem is that I don't know how to input this dataset into any of these functions
#I dont understand what format it needs or really even what I am plotting
#changing to an array didnt do anything

ValueError: could not convert string to float: '?'

In [9]:
# Trying the elbow method here...again referencing how it was done in the article 
distortions = []
for i in range(1, 11):  #why 1 to 11????
    km = KMeans(
        n_clusters=i, init='random',
        n_init=10, max_iter=300,
        tol=1e-04, random_state=0
    )
    km.fit(arrhythmia_array)
    distortions.append(km.inertia_)

# plot
plt.plot(range(1, 11), distortions, marker='o')
plt.xlabel('Number of clusters')
plt.ylabel('Distortion')
plt.show()

#predicatably got the same error
#Don't understand how to input data into any of the machine learning things, or why there are 16 clusters in the data...

ValueError: could not convert string to float: '?'